
package org.pcConfigurator.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DeliveryPortService", targetNamespace = "http://spring.io/guides/gs-producing-web-service", wsdlLocation = "http://localhost:8090/ws/delivery.wsdl")
public class DeliveryPortService
    extends Service
{

    private final static URL DELIVERYPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException DELIVERYPORTSERVICE_EXCEPTION;
    private final static QName DELIVERYPORTSERVICE_QNAME = new QName("http://spring.io/guides/gs-producing-web-service", "DeliveryPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/ws/delivery.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DELIVERYPORTSERVICE_WSDL_LOCATION = url;
        DELIVERYPORTSERVICE_EXCEPTION = e;
    }

    public DeliveryPortService() {
        super(__getWsdlLocation(), DELIVERYPORTSERVICE_QNAME);
    }

    public DeliveryPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DELIVERYPORTSERVICE_QNAME, features);
    }

    public DeliveryPortService(URL wsdlLocation) {
        super(wsdlLocation, DELIVERYPORTSERVICE_QNAME);
    }

    public DeliveryPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DELIVERYPORTSERVICE_QNAME, features);
    }

    public DeliveryPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeliveryPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DeliveryPort
     */
    @WebEndpoint(name = "DeliveryPortSoap11")
    public DeliveryPort getDeliveryPortSoap11() {
        return super.getPort(new QName("http://spring.io/guides/gs-producing-web-service", "DeliveryPortSoap11"), DeliveryPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeliveryPort
     */
    @WebEndpoint(name = "DeliveryPortSoap11")
    public DeliveryPort getDeliveryPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://spring.io/guides/gs-producing-web-service", "DeliveryPortSoap11"), DeliveryPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DELIVERYPORTSERVICE_EXCEPTION!= null) {
            throw DELIVERYPORTSERVICE_EXCEPTION;
        }
        return DELIVERYPORTSERVICE_WSDL_LOCATION;
    }

}
